[tool.poetry]
name = "eits-python-api"
version = "0.1.0"
description = "Python library for using E-ITS portal API."
authors = ["Marco Sepp <marco@frontmeedia.ee>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
python-dotenv = "^1.2.3"
pydantic = "^2.13.4"
aiohttp = "^3.14.3"
lxml = ">=6.1.1,<7.0.0"
beautifulsoup4 = "^4.15.0"
requests = "^2.34.2"
regex = ">=2024.7.24,<2027.0.0"
pytest = ">=8.3.2,<10.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
